<a href="https://colab.research.google.com/github/Arghyajyoti007/Pandas-Overview/blob/main/Pandas_Overview.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# Data Frame
data = {
    "name" : ["Arghya","Sonai"],
    "age" :[24,24]
}
df = pd.DataFrame(data)
print(df)

     name  age
0  Arghya   24
1   Sonai   24

In [ ]:
data = [10, 20, 30, "Arghya"]
series1 = pd.Series(data)
print(series1)
series2 = pd.Series(data, index=["a", "b", "c", "d"])
print(series2)

0        10
1        20
2        30
3    Arghya
dtype: object
a        10
b        20
c        30
d    Arghya
dtype: object

In [ ]:
# Exploring data in pandas

import pandas as pd
import numpy as np

data = np.random.uniform(10, 50, (7,8))
df_large = pd.DataFrame(data, columns=[f'col_{i}' for i in range(8)])
print(df_large)
print(df_large.head())
print(df_large.tail())
print(df_large.info())
print(df_large.describe())
print(df_large.dtypes)
print(df_large.shape)
print(df_large.columns)
print(df_large['col_1'].unique())
print(df_large['col_3'].nunique())
print(df_large['col_5'].value_counts())

       col_0      col_1      col_2      col_3      col_4      col_5  \
0  22.041541  18.448654  22.576794  18.634386  20.189643  38.930018
1  42.936067  44.729799  38.963152  47.832159  19.443673  34.549477
2  17.385902  49.447349  40.413244  15.622372  34.105914  34.717038
3  46.850201  32.180957  27.826787  29.975137  36.768809  38.080244
4  16.299756  27.842890  28.451095  41.600663  32.503904  35.242015
5  41.832842  26.846817  43.283010  15.299228  40.030591  47.383552
6  17.955214  29.237576  48.564455  44.479656  17.353880  18.600792

       col_6      col_7
0  44.865525  14.661403
1  40.922380  20.986729
2  25.875118  28.607730
3  42.952204  13.363387
4  35.783655  10.892315
5  24.694410  16.253605
6  44.828760  10.345531
       col_0      col_1      col_2      col_3      col_4      col_5  \
0  22.041541  18.448654  22.576794  18.634386  20.189643  38.930018
1  42.936067  44.729799  38.963152  47.832159  19.443673  34.549477
2  17.385902  49.447349  40.413244  15.622372  34.105914  34.717038
3  46.850201  32.180957  27.826787  29.975137  36.768809  38.080244
4  16.299756  27.842890  28.451095  41.600663  32.503904  35.242015

       col_6      col_7
0  44.865525  14.661403
1  40.922380  20.986729
2  25.875118  28.607730
3  42.952204  13.363387
4  35.783655  10.892315
       col_0      col_1      col_2      col_3      col_4      col_5  \
2  17.385902  49.447349  40.413244  15.622372  34.105914  34.717038
3  46.850201  32.180957  27.826787  29.975137  36.768809  38.080244
4  16.299756  27.842890  28.451095  41.600663  32.503904  35.242015
5  41.832842  26.846817  43.283010  15.299228  40.030591  47.383552
6  17.955214  29.237576  48.564455  44.479656  17.353880  18.600792

       col_6      col_7
2  25.875118  28.607730
3  42.952204  13.363387
4  35.783655  10.892315
5  24.694410  16.253605
6  44.828760  10.345531
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col_0   7 non-null      float64
 1   col_1   7 non-null      float64
 2   col_2   7 non-null      float64
 3   col_3   7 non-null      float64
 4   col_4   7 non-null      float64
 5   col_5   7 non-null      float64
 6   col_6   7 non-null      float64
 7   col_7   7 non-null      float64
dtypes: float64(8)
memory usage: 580.0 bytes
None
           col_0      col_1      col_2      col_3      col_4      col_5  \
count   7.000000   7.000000   7.000000   7.000000   7.000000   7.000000
mean   29.328789  32.676292  35.725505  30.491943  28.628059  35.357591
std    13.804345  10.788850   9.509707  14.215803   9.345101   8.628111
min    16.299756  18.448654  22.576794  15.299228  17.353880  18.600792
25%    17.670558  27.344854  28.138941  17.128379  19.816658  34.633258
50%    22.041541  29.237576  38.963152  29.975137  32.503904  35.242015
75%    42.384454  38.455378  41.848127  43.040160  35.437361  38.505131
max    46.850201  49.447349  48.564455  47.832159  40.030591  47.383552

           col_6      col_7
count   7.000000   7.000000
mean   37.131722  16.444386
std     8.665240   6.446049
min    24.694410  10.345531
25%    30.829387  12.127851
50%    40.922380  14.661403
75%    43.890482  18.620167
max    44.865525  28.607730
col_0    float64
col_1    float64
col_2    float64
col_3    float64
col_4    float64
col_5    float64
col_6    float64
col_7    float64
dtype: object
(7, 8)
Index(['col_0', 'col_1', 'col_2', 'col_3', 'col_4', 'col_5', 'col_6', 'col_7'], dtype='object')
[18.44865435 44.72979861 49.44734851 32.1809575  27.84288972 26.84681741
 29.23757569]
7
col_5
38.930018    1
34.549477    1
34.717038    1
38.080244    1
35.242015    1
47.383552    1
18.600792    1
Name: count, dtype: int64

In [ ]:
# Indexing and Selection in Pandas
# loc
data = np.random.rand(3,4)
df = pd.DataFrame(data, columns=['A','B','C','D'], index=[1,2,3])
print(df)
print(df.loc[1])
print(df.loc[[1,2]])
print(df.loc[1,'B'])
print(df.loc[[1,2],['A']])
print(df.loc[:,['C']])
print(df.loc[1:3,['A','B']])

          A         B         C         D
1  0.085081  0.707312  0.165648  0.959608
2  0.476205  0.475118  0.202728  0.110409
3  0.466770  0.698954  0.691207  0.331390
A    0.085081
B    0.707312
C    0.165648
D    0.959608
Name: 1, dtype: float64
          A         B         C         D
1  0.085081  0.707312  0.165648  0.959608
2  0.476205  0.475118  0.202728  0.110409
0.707311993473032
          A
1  0.085081
2  0.476205
          C
1  0.165648
2  0.202728
3  0.691207
          A         B
1  0.085081  0.707312
2  0.476205  0.475118
3  0.466770  0.698954

In [ ]:
# iloc
print(df)
print(df.iloc[1])
print(df.iloc[[0,2]])
print(df.iloc[1,3])
print(df.iloc[0:2,0:2])
print(df.iloc[1:3,:])

          A         B         C         D
1  0.085081  0.707312  0.165648  0.959608
2  0.476205  0.475118  0.202728  0.110409
3  0.466770  0.698954  0.691207  0.331390
A    0.476205
B    0.475118
C    0.202728
D    0.110409
Name: 2, dtype: float64
          A         B         C         D
1  0.085081  0.707312  0.165648  0.959608
3  0.466770  0.698954  0.691207  0.331390
0.110408562322453
          A         B
1  0.085081  0.707312
2  0.476205  0.475118
          A         B         C         D
2  0.476205  0.475118  0.202728  0.110409
3  0.466770  0.698954  0.691207  0.331390

In [ ]:
import numpy as np
import pandas as pd

# Creating a DataFrame for conditional selection
data = np.random.uniform(3,50, (3,4))
df = pd.DataFrame(data, columns=['A','B','C','D'], index=[1,2,3])

print(df)
print(df[df > 25])
print(df[df['A'] > 25])
print(df[(df['A'] > 25) & (df['B'] < 10)])
print(df[(df['A'] > 25) | (df['B'] < 10)])
print(df.query('A > 25 and B > 20'))
print(df.query('not (A > 25 and B > 20)'))
print(df[~(df['A'] < 40)])
print(df[df['C'].isin([25,30])])

           A          B          C          D
1  45.544244  10.567413  34.375200  19.535028
2   5.016769  15.748146  30.453802   8.513235
3  48.087021   5.991526  43.516100  24.687922
           A   B          C   D
1  45.544244 NaN  34.375200 NaN
2        NaN NaN  30.453802 NaN
3  48.087021 NaN  43.516100 NaN
           A          B        C          D
1  45.544244  10.567413  34.3752  19.535028
3  48.087021   5.991526  43.5161  24.687922
           A         B        C          D
3  48.087021  5.991526  43.5161  24.687922
           A          B        C          D
1  45.544244  10.567413  34.3752  19.535028
3  48.087021   5.991526  43.5161  24.687922
Empty DataFrame
Columns: [A, B, C, D]
Index: []
           A          B          C          D
1  45.544244  10.567413  34.375200  19.535028
2   5.016769  15.748146  30.453802   8.513235
3  48.087021   5.991526  43.516100  24.687922
           A          B        C          D
1  45.544244  10.567413  34.3752  19.535028
3  48.087021   5.991526  43.5161  24.687922
Empty DataFrame
Columns: [A, B, C, D]
Index: []

### Sample DataFrame for Data Manipulation

This DataFrame includes:
- `Name`: Categorical data (strings).
- `Age`: Numerical data (integers).
- `City`: Categorical data with some missing values (`NaN`).
- `Salary`: Numerical data (floats) with some missing values.
- `Department`: Categorical data, showcasing different departments.

In [ ]:
import pandas as pd
import numpy as np

# Create a sample DataFrame
data_manipulation_df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Heidi'],
    'Age': [25, 30, 35, 28, 40, 32, 27, 45],
    'City': ['New York', 'London', np.nan, 'Paris', 'Tokyo', 'London', 'New York', np.nan],
    'Salary': [70000.0, 85000.0, 60000.0, np.nan, 95000.0, 78000.0, 62000.0, 110000.0],
    'Department': ['HR', 'Engineering', 'HR', 'Sales', 'Engineering', 'Finance', 'Sales', 'Engineering']
})

print("Sample DataFrame for Data Manipulation:")
display(data_manipulation_df)

# Manupulating Data or Data Manupulation

# Adding new Column
data_manipulation_df["Last Name"] = ["Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis"]
# Rename Column
data_manipulation_df = data_manipulation_df.rename(columns={'Name':'First Name'})
# Change Datatype
data_manipulation_df['Age'] = data_manipulation_df['Age'].astype(float) # Corrected line
# Replace Values
data_manipulation_df['City'] = data_manipulation_df["City"].replace({np.nan : "Unknown"})
# Remove Column
data_manipulation_df = data_manipulation_df.drop('City', axis = 1)

print("Sample DataFrame for Data Manipulation Post Changes:")
display(data_manipulation_df)

Sample DataFrame for Data Manipulation:

      Name  Age      City    Salary   Department
0    Alice   25  New York   70000.0           HR
1      Bob   30    London   85000.0  Engineering
2  Charlie   35       NaN   60000.0           HR
3    David   28     Paris       NaN        Sales
4      Eve   40     Tokyo   95000.0  Engineering
5    Frank   32    London   78000.0      Finance
6    Grace   27  New York   62000.0        Sales
7    Heidi   45       NaN  110000.0  Engineering

Sample DataFrame for Data Manipulation Post Changes:

  First Name   Age    Salary   Department Last Name
0      Alice  25.0   70000.0           HR     Smith
1        Bob  30.0   85000.0  Engineering   Johnson
2    Charlie  35.0   60000.0           HR  Williams
3      David  28.0       NaN        Sales     Brown
4        Eve  40.0   95000.0  Engineering     Jones
5      Frank  32.0   78000.0      Finance    Garcia
6      Grace  27.0   62000.0        Sales    Miller
7      Heidi  45.0  110000.0  Engineering     Davis

### Sample DataFrame for Null Management

This DataFrame is designed to demonstrate different scenarios of missing values:
- `ID`: Unique identifier, no missing values.
- `Value_A`: Numerical data with some missing values.
- `Category`: Categorical data with missing values.
- `Date`: Datetime objects, some of which are missing.
- `Notes`: Textual data with some missing entries.
- `Empty_Column`: A column with all values missing.

In [ ]:
import pandas as pd
import numpy as np

# Create a sample DataFrame with null values
null_management_df = pd.DataFrame({
    'ID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Value_A': [10.5, np.nan, 12.3, 14.1, np.nan, 16.7, 18.2, 19.0, np.nan, 21.5],
    'Category': ['A', 'B', np.nan, 'C', 'A', 'B', 'C', np.nan, 'A', 'B'],
    'Date': pd.to_datetime(['2023-01-01', '2023-01-02', np.nan, '2023-01-04', '2023-01-05', np.nan, '2023-01-07', '2023-01-08', '2023-01-09', '2023-01-10']),
    'Notes': ['First entry', np.nan, 'Third entry', 'Fourth entry', np.nan, 'Sixth entry', np.nan, 'Eighth entry', 'Ninth entry', 'Tenth entry'],
    'Empty_Column': [np.nan] * 10
})

print("Sample DataFrame for Null Management:")
display(null_management_df)

print("\nInformation about null values:")
display(null_management_df.isnull())
display(null_management_df.isnull().sum())
display(null_management_df['Notes'].isnull().sum())

print("\nRemoving Null Values: ")
display(null_management_df.dropna()) # This creates a new DataFrame without modifying the original
display(null_management_df.dropna(axis = 1))
display(null_management_df.dropna(subset = ['Value_A']))
display(null_management_df.dropna(how='all'))

# Assign a copy of the original DataFrame to df for further operations
df = null_management_df.copy()

# If you wanted to permanently drop rows with any NaNs, you would do:
# null_management_df.dropna(inplace = True)
# However, in this case, it would make the DataFrame empty, so we won't do it here.
display(null_management_df) # Display original (unmodified) null_management_df

print('\nFilling Null Values: ')
display(df) # Display the copy used for filling
display(df.fillna("Unknown"))
display(df.fillna(method = "ffill"))
display(df.fillna(method = "bfill")) # Corrected typo from nmethod to method

mean = df['Value_A'].mean()
median = df['Value_A'].median()

# The mode() method in pandas returns a Series because a dataset might have multiple values that occur with the highest frequency (i.e., multiple modes).
# By adding [0] to df['Value_A'].mode(), you are selecting the first mode from that Series.
# This is a common practice when you need to use a single scalar value, for example, to fill missing data,
# even if there are multiple modes present in the column.
mode = df['Value_A'].mode()[0]

# To actually modify the DataFrame, assign the result back to the column
df['Value_A'] = df['Value_A'].fillna(mean)
display(df)

Sample DataFrame for Null Management:

   ID  Value_A Category       Date         Notes  Empty_Column
0   1     10.5        A 2023-01-01   First entry           NaN
1   2      NaN        B 2023-01-02           NaN           NaN
2   3     12.3      NaN        NaT   Third entry           NaN
3   4     14.1        C 2023-01-04  Fourth entry           NaN
4   5      NaN        A 2023-01-05           NaN           NaN
5   6     16.7        B        NaT   Sixth entry           NaN
6   7     18.2        C 2023-01-07           NaN           NaN
7   8     19.0      NaN 2023-01-08  Eighth entry           NaN
8   9      NaN        A 2023-01-09   Ninth entry           NaN
9  10     21.5        B 2023-01-10   Tenth entry           NaN

Information about null values:

      ID  Value_A  Category   Date  Notes  Empty_Column
0  False    False     False  False  False          True
1  False     True     False  False   True          True
2  False    False      True   True  False          True
3  False    False     False  False  False          True
4  False     True     False  False   True          True
5  False    False     False   True  False          True
6  False    False     False  False   True          True
7  False    False      True  False  False          True
8  False     True     False  False  False          True
9  False    False     False  False  False          True

ID               0
Value_A          3
Category         2
Date             2
Notes            3
Empty_Column    10
dtype: int64

np.int64(3)

Removing Null Values:

Empty DataFrame
Columns: [ID, Value_A, Category, Date, Notes, Empty_Column]
Index: []

   ID
0   1
1   2
2   3
3   4
4   5
5   6
6   7
7   8
8   9
9  10

   ID  Value_A Category       Date         Notes  Empty_Column
0   1     10.5        A 2023-01-01   First entry           NaN
2   3     12.3      NaN        NaT   Third entry           NaN
3   4     14.1        C 2023-01-04  Fourth entry           NaN
5   6     16.7        B        NaT   Sixth entry           NaN
6   7     18.2        C 2023-01-07           NaN           NaN
7   8     19.0      NaN 2023-01-08  Eighth entry           NaN
9  10     21.5        B 2023-01-10   Tenth entry           NaN

   ID  Value_A Category       Date         Notes  Empty_Column
0   1     10.5        A 2023-01-01   First entry           NaN
1   2      NaN        B 2023-01-02           NaN           NaN
2   3     12.3      NaN        NaT   Third entry           NaN
3   4     14.1        C 2023-01-04  Fourth entry           NaN
4   5      NaN        A 2023-01-05           NaN           NaN
5   6     16.7        B        NaT   Sixth entry           NaN
6   7     18.2        C 2023-01-07           NaN           NaN
7   8     19.0      NaN 2023-01-08  Eighth entry           NaN
8   9      NaN        A 2023-01-09   Ninth entry           NaN
9  10     21.5        B 2023-01-10   Tenth entry           NaN

   ID  Value_A Category       Date         Notes  Empty_Column
0   1     10.5        A 2023-01-01   First entry           NaN
1   2      NaN        B 2023-01-02           NaN           NaN
2   3     12.3      NaN        NaT   Third entry           NaN
3   4     14.1        C 2023-01-04  Fourth entry           NaN
4   5      NaN        A 2023-01-05           NaN           NaN
5   6     16.7        B        NaT   Sixth entry           NaN
6   7     18.2        C 2023-01-07           NaN           NaN
7   8     19.0      NaN 2023-01-08  Eighth entry           NaN
8   9      NaN        A 2023-01-09   Ninth entry           NaN
9  10     21.5        B 2023-01-10   Tenth entry           NaN

Filling Null Values:

   ID  Value_A Category       Date         Notes  Empty_Column
0   1     10.5        A 2023-01-01   First entry           NaN
1   2      NaN        B 2023-01-02           NaN           NaN
2   3     12.3      NaN        NaT   Third entry           NaN
3   4     14.1        C 2023-01-04  Fourth entry           NaN
4   5      NaN        A 2023-01-05           NaN           NaN
5   6     16.7        B        NaT   Sixth entry           NaN
6   7     18.2        C 2023-01-07           NaN           NaN
7   8     19.0      NaN 2023-01-08  Eighth entry           NaN
8   9      NaN        A 2023-01-09   Ninth entry           NaN
9  10     21.5        B 2023-01-10   Tenth entry           NaN

   ID  Value_A Category                 Date         Notes Empty_Column
0   1     10.5        A  2023-01-01 00:00:00   First entry      Unknown
1   2  Unknown        B  2023-01-02 00:00:00       Unknown      Unknown
2   3     12.3  Unknown              Unknown   Third entry      Unknown
3   4     14.1        C  2023-01-04 00:00:00  Fourth entry      Unknown
4   5  Unknown        A  2023-01-05 00:00:00       Unknown      Unknown
5   6     16.7        B              Unknown   Sixth entry      Unknown
6   7     18.2        C  2023-01-07 00:00:00       Unknown      Unknown
7   8     19.0  Unknown  2023-01-08 00:00:00  Eighth entry      Unknown
8   9  Unknown        A  2023-01-09 00:00:00   Ninth entry      Unknown
9  10     21.5        B  2023-01-10 00:00:00   Tenth entry      Unknown

/tmp/ipykernel_1579/2928404592.py:39: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  display(df.fillna(method = "ffill"))

   ID  Value_A Category       Date         Notes  Empty_Column
0   1     10.5        A 2023-01-01   First entry           NaN
1   2     10.5        B 2023-01-02   First entry           NaN
2   3     12.3        B 2023-01-02   Third entry           NaN
3   4     14.1        C 2023-01-04  Fourth entry           NaN
4   5     14.1        A 2023-01-05  Fourth entry           NaN
5   6     16.7        B 2023-01-05   Sixth entry           NaN
6   7     18.2        C 2023-01-07   Sixth entry           NaN
7   8     19.0        C 2023-01-08  Eighth entry           NaN
8   9     19.0        A 2023-01-09   Ninth entry           NaN
9  10     21.5        B 2023-01-10   Tenth entry           NaN

/tmp/ipykernel_1579/2928404592.py:40: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  display(df.fillna(method = "bfill")) # Corrected typo from nmethod to method

   ID  Value_A Category       Date         Notes  Empty_Column
0   1     10.5        A 2023-01-01   First entry           NaN
1   2     12.3        B 2023-01-02   Third entry           NaN
2   3     12.3        C 2023-01-04   Third entry           NaN
3   4     14.1        C 2023-01-04  Fourth entry           NaN
4   5     16.7        A 2023-01-05   Sixth entry           NaN
5   6     16.7        B 2023-01-07   Sixth entry           NaN
6   7     18.2        C 2023-01-07  Eighth entry           NaN
7   8     19.0        A 2023-01-08  Eighth entry           NaN
8   9     21.5        A 2023-01-09   Ninth entry           NaN
9  10     21.5        B 2023-01-10   Tenth entry           NaN

   ID    Value_A Category       Date         Notes  Empty_Column
0   1  10.500000        A 2023-01-01   First entry           NaN
1   2  16.042857        B 2023-01-02           NaN           NaN
2   3  12.300000      NaN        NaT   Third entry           NaN
3   4  14.100000        C 2023-01-04  Fourth entry           NaN
4   5  16.042857        A 2023-01-05           NaN           NaN
5   6  16.700000        B        NaT   Sixth entry           NaN
6   7  18.200000        C 2023-01-07           NaN           NaN
7   8  19.000000      NaN 2023-01-08  Eighth entry           NaN
8   9  16.042857        A 2023-01-09   Ninth entry           NaN
9  10  21.500000        B 2023-01-10   Tenth entry           NaN